title: Roshan Ranadeerage
logo: /assets/img/logo.png
description: Welcome to my portfolio page!<br><br>Base SAS Programming Certified Specialist (SAS 9.4) with over ten years of experience in data manipulation, data modelling, optimization, statistical programming, visualization, data analysis, and data management. Passionate about AI, data science, and delivering solutions across diverse domains and scales.<br><br> Snowflake, SQL, Python, R, SAS, MySQL, Shiny, Tableau, Power BI, Excel <br><br> Based in London, United Kingdom.
show_downloads: true
google_analytics: G-4DQ05PW5JK
theme: jekyll-theme-minimal
